import resend
from ..config import settings

resend.api_key = settings.resend_api_key

async def send_recipe_email(to_email: str, recipe_data: dict):
    """Send recipe via email using Resend"""
    
    # Format ingredients
    ingredients_html = "<ul>"
    for ing in recipe_data.get("ingredients", []):
        name = ing.get("name", "")
        quantity = ing.get("quantity", "")
        unit = ing.get("unit", "")
        ingredients_html += f"<li>{quantity} {unit} {name}</li>"
    ingredients_html += "</ul>"
    
    # Format instructions
    instructions_html = "<ol>"
    for step in recipe_data.get("instructions", []):
        instructions_html += f"<li>{step}</li>"
    instructions_html += "</ol>"
    
    # Create email HTML
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background: linear-gradient(135deg, #FF6B35 0%, #FFC107 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }}
            .content {{ background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }}
            h1 {{ margin: 0; font-size: 28px; }}
            h2 {{ color: #FF6B35; }}
            ul, ol {{ padding-left: 20px; }}
            li {{ margin-bottom: 8px; }}
            .meta {{ background: white; padding: 15px; border-radius: 8px; margin: 20px 0; }}
            .meta span {{ display: inline-block; margin-right: 20px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🍽️ {recipe_data.get("title", "Recipe")}</h1>
            </div>
            <div class="content">
                <p>{recipe_data.get("description", "")}</p>
                
                <div class="meta">
                    <span>⏱️ <strong>{recipe_data.get("cooking_time", "N/A")} minutes</strong></span>
                    <span>👥 <strong>{recipe_data.get("servings", "N/A")} servings</strong></span>
                    <span>📊 <strong>{recipe_data.get("difficulty", "medium").title()}</strong></span>
                    <span>🌍 <strong>{recipe_data.get("cuisine", "Global")}</strong></span>
                </div>
                
                <h2>Ingredients</h2>
                {ingredients_html}
                
                <h2>Instructions</h2>
                {instructions_html}
                
                {f"<h2>Tips</h2><ul>{''.join([f'<li>{tip}</li>' for tip in recipe_data.get('tips', [])])}</ul>" if recipe_data.get('tips') else ""}
                
                <hr style="margin: 30px 0; border: none; border-top: 1px solid #ddd;">
                <p style="text-align: center; color: #888; font-size: 14px;">
                    This recipe was generated by Recipe AI<br>
                    <a href="{settings.frontend_url}" style="color: #FF6B35;">Visit Recipe AI</a>
                </p>
            </div>
        </div>
    </body>
    </html>
    """
    
    params = {
        "from": "Recipe AI <onboarding@resend.dev>",  # Use your verified domain
        "to": [to_email],
        "subject": f"Your Recipe: {recipe_data.get('title', 'Delicious Recipe')}",
        "html": html_content,
    }
    
    result = resend.Emails.send(params)
    return result
