from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from io import BytesIO

def generate_recipe_pdf(recipe_data: dict) -> BytesIO:
    """Generate a PDF file from recipe data"""
    
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#FF6B35'),
        spaceAfter=12,
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#4CAF50'),
        spaceAfter=10,
        spaceBefore=12,
    )
    
    # Title
    title = Paragraph(recipe_data.get("title", "Recipe"), title_style)
    story.append(title)
    story.append(Spacer(1, 0.2*inch))
    
    # Description
    if recipe_data.get("description"):
        desc = Paragraph(recipe_data.get("description"), styles['Normal'])
        story.append(desc)
        story.append(Spacer(1, 0.2*inch))
    
    # Meta information table
    meta_data = [
        ['Cooking Time', f"{recipe_data.get('cooking_time', 'N/A')} minutes"],
        ['Servings', str(recipe_data.get('servings', 'N/A'))],
        ['Difficulty', recipe_data.get('difficulty', 'medium').title()],
        ['Cuisine', recipe_data.get('cuisine', 'Global')],
    ]
    
    meta_table = Table(meta_data, colWidths=[2*inch, 3*inch])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
    ]))
    
    story.append(meta_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Ingredients
    ingredients_heading = Paragraph("Ingredients", heading_style)
    story.append(ingredients_heading)
    
    for ing in recipe_data.get("ingredients", []):
        name = ing.get("name", "")
        quantity = ing.get("quantity", "")
        unit = ing.get("unit", "")
        ing_text = f"• {quantity} {unit} {name}"
        ing_para = Paragraph(ing_text, styles['Normal'])
        story.append(ing_para)
        story.append(Spacer(1, 0.1*inch))
    
    story.append(Spacer(1, 0.2*inch))
    
    # Instructions
    instructions_heading = Paragraph("Instructions", heading_style)
    story.append(instructions_heading)
    
    for i, step in enumerate(recipe_data.get("instructions", []), 1):
        step_text = f"{i}. {step}"
        step_para = Paragraph(step_text, styles['Normal'])
        story.append(step_para)
        story.append(Spacer(1, 0.15*inch))
    
    # Tips
    if recipe_data.get("tips"):
        story.append(Spacer(1, 0.2*inch))
        tips_heading = Paragraph("Tips", heading_style)
        story.append(tips_heading)
        
        for tip in recipe_data.get("tips", []):
            tip_text = f"💡 {tip}"
            tip_para = Paragraph(tip_text, styles['Normal'])
            story.append(tip_para)
            story.append(Spacer(1, 0.1*inch))
    
    # Footer
    story.append(Spacer(1, 0.5*inch))
    footer = Paragraph(
        "<i>Generated by Recipe AI - Your AI-Powered Recipe Assistant</i>",
        styles['Normal']
    )
    story.append(footer)
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer
